### ISSUE TITLE
Very impressive

### ISSUE THREAD

**Issue by Khang-NT** [L-JINBIN/ApkSignatureKiller#5]
Your work is very impressive. Are you `biN32`? Can you make another mod version of YMusic app? I'm able to detect you proxying `interface IPackageManager`, are you interested in making another solution?

**Comment by uqsme** [comment]
Actually he's the author of MT Manager, an Android app, which can be found in Play Store. As far as I know, he won't support this project any longer, but a updated version is built in MT Manager, you may have a try.
